name: dump_viz
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/dump-info-visualizer/
description: A visualizer for the JSON data produced by the dart2js --dump-info command
environment:
  sdk: '>=1.11.0-dev <2.0.0'
dependencies:
  core_elements: '^0.7.1+2'
  paper_elements: '^0.7.1'
  path: '^1.3.5'
  polymer: '^0.16.3+1'
dev_dependencies:
  test: '^0.12.0'
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    $include: "**/*.polymer.bootstrap.dart"
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
    - --dump-info
