name: _dummy_pkg
homepage: 'https://github.com/dart-lang/pub-dev'
description: 'Dummy packages published from pub integration tests.'
dependencies:
  retry: ^2.0.0
environment:
  sdk: ">=2.1.0 <3.0.0"
