name: group_changes_functions
version: 0.1.0
author: "Dart Team <misc@dartlang.org>"
description: >-
  A Firebase cloud function that processes new changes

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  collection: ^1.14.12
  firebase_functions_interop: ^1.0.2
  pool: ^1.4.0
  retry: ^3.0.0

dev_dependencies:
  build_runner: ^1.7.1
  build_node_compilers: ^0.2.3
  mockito: ^4.1.0
  test: ^1.9.4
