name: dart_results_feed
description: The Dart results feed in Angular using Firebase
version: 0.0.1

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: '>=0.13.0'
  angular_forms: ^2.0.0-alpha
  angular_router: ^2.0.0-alpha+22
  firebase: ^7.0.0
  http: ^0.12.0
  intl: ^0.15.0
  protobuf: ">=0.13.6"
  quiver: ^2.1.0
  service_worker: ^0.2.2

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^2.1.0
  build_test: ^0.10.2
  pageloader: ^3.2.0
  pedantic: ^1.9.0
  sass_builder: ^2.1.0
  test: ^1.0.0
