name: client_data
description: Shared data between server and JS client.
publish_to: none
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  json_annotation: '^3.0.0'
  meta: ^1.1.5

dev_dependencies:
  build_runner: '^1.0.0'
  build_verify: ^1.1.1
  json_serializable: '^3.0.0'
  source_gen: '^0.9.0'
  test: '^1.3.0'
