name: _popularity
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.1
  json_serializable: ^3.0.0
  test: ^1.3.0
